#!/bin/bash
# integrity.sh — checkpoint. Hashes every tracked source file.
# Compare against .integrity-baseline; any diff not written by me is quarantined.
# Incident 4 taught the gap: root files are covered too, this script included.
# Session 9 taught the next one: the EXTENSION WHITELIST was itself a blind spot.
# api/bobby.mjs — the deployed Claude proxy holding the key injection and the
# model allowlist — sat in a scanned directory and was invisible because the
# filter listed .js and the file is .mjs. Seven others were invisible too: the
# .xlsx test fixtures the Data Doc suites assert against, the mining Journey and
# Config docs, .github/, .env.example and momentum-Simulation_19.html.
# A whitelist is correct the day it is written and silently wrong the first time
# someone adds a file type. Coverage is now EVERY file in a source directory —
# binaries included — so an exclusion has to be deliberate rather than accidental.
# Known and expected: test/mining-config.csv is gitignored and generated by
# `npm run pregate`, so a fresh unpack differs by that one line until pregate runs.
# .integrity-baseline cannot cover itself; its own md5 belongs in the transcript.
cd "$(dirname "$0")"
{ find src api test build config harness supabase .github -type f 2>/dev/null;
  ls package.json package-lock.json vercel.json .gitignore .env.example CLAUDE.md README.md integrity.sh momentum-Simulation_19.html 2>/dev/null; } | sort | xargs md5sum
