#!/bin/bash
# integrity.sh — checkpoint. Hashes every tracked source file.
# Compare against .integrity-baseline; any diff not written by me is quarantined.
#
# THREE LESSONS, EACH A WHITELIST THAT WENT STALE:
#   Incident 4  root files were not covered at all. Fixed by naming them.
#   Session 9   the EXTENSION whitelist was a blind spot. api/bobby.mjs — the
#               deployed Claude proxy holding the key injection and the model
#               allowlist — sat in a scanned directory and was invisible only
#               because the filter listed .js and the file is .mjs. Eight
#               others were too: the .xlsx Data Doc fixtures the suites assert
#               against, the mining Journey and Config docs, .github/,
#               .env.example, momentum-Simulation_19.html. Fixed by dropping
#               the extension filter.
#   Session 9   the ROOT-FILE NAMED LIST was the last one standing, and the
#   (later)     pnpm migration walked straight into it: package-lock.json was
#               named, pnpm-lock.yaml was not, so the lockfile that pins every
#               dependency of a deployed app became invisible the moment it
#               was renamed. Found by the developer. Fixed here.
#
# The repeated shape is a list of what to INCLUDE. Such a list is correct the
# day it is written and silently wrong the first time someone adds something.
# So the rule is inverted: everything is covered unless it is deliberately
# excluded, and the exclusions are generated output only — named below, with
# the reason each one is there. A new file at the root is now covered by
# default. If that ever produces a surprise, the surprise is the point.
#
# EXPECTED DIFFERENCES, which are not incidents:
#   test/mining-config.csv  gitignored, generated by `npm run pregate`, so a
#                           fresh unpack differs by that one line until it runs.
#   .integrity-baseline     cannot hash itself. Its own md5 belongs in the
#                           transcript, which is the tamper-resistant register.
cd "$(dirname "$0")"

# Generated at the root by `npm run pregate`, `node build/build.js` or the
# visual suites. Excluded because they are outputs, not sources — hashing them
# would make the baseline depend on whether a build had been run.
EXCLUDE='^\./(p20\.json|momentum-Simulation_68\.html|shot.*\.png|\.integrity-baseline|\.env)$'

{ find src api test build config harness supabase .github -type f 2>/dev/null;
  find . -maxdepth 1 -type f 2>/dev/null | grep -Ev "$EXCLUDE" | sed 's|^\./||'; } \
  | sort -u | xargs md5sum
